---
title: "our results"
---

Our analysis is not the first of it's kind. A similar [study](https://www.bjs.gov/index.cfm?ty=tp&tid=702) was done by the Bureau of Justic Statistics, who found that only about 68% of black drivers felt they were stopped by a legitimate reason for the police. 
Our analysis indicates that in Charlotte, at least, this feeling may be founded. The finding that stuck out most to us in our initial explorations was that roughly 50% of stopped drivers in Charlotte were black, but black people make up only about 35% of Charlotte's population. After doing subsequent t-tests on the proportion of stopped drivers compared to the population of drivers of that race in the population, we found that this discrepancy was significant. 

Charlotte, like a lot of major cities in the South, is geographically and economically segregated along racial lines. Just by demography alone, you wouldn't know - by percentage, Charlotte has more minorities than the US on average. This [analysis](https://fivethirtyeight.com/features/the-most-diverse-cities-are-often-the-most-segregated/) from 538 confirms. 

Our logistic regression seemed to fit our test data well, but given the nature of the sample and the variables we chose to focus on it's unclear if there are other factors at play. 

Overall, we learned a lot from this project (most importantly, how to code icons in an rmarkdown site), and we look forward to using the tools learned in future analysis.
